#!/usr/bin/env perl
use strict;
use warnings;

while (<>) {
    chomp;
    my $user = $_;

    system qq[mkdir -p "out/$user"];
    my @tracks = split /^/, qx[$^X get-osm-gpx-tracks-for-user --debug "$_"];

    next unless @tracks;

    my $count = 1;

    for my $track (@tracks) {
        chomp $track;
        my ($num) = $track =~ m[/trace/(\d+)/];
        system qq[wget -q $track -O /tmp/track];
        my $what = `file /tmp/track`;
        if ($what =~ /gzip compressed data/) {
            system qq[cat /tmp/track | gzip -d > "out/$user/$num.gpx"];
            system qq[rm /tmp/track];
        } else {
            system qq[mv /tmp/track "out/$user/$num.gpx"];
        }

        printf "Downloaded track %d/%d\n", $count++, scalar @tracks;
    }
}
